Numpy is a fundamental library for scientific computing in python. it provides suport for array and matrices, along with the collection of mathemmatical functions to operate on these data structures. in this lesson we will learn the basics of numpy, focusing on arrays and vectorized operations.


In [ ]:
! pip install numpy

In [3]:
import numpy as np

## create array using numpy
## single dimension array (1D array)
arr1 = np.array([1,2,3,4,5])
print("array",arr1)
print(type(arr1))
print("shape",arr1.shape )

array [1 2 3 4 5]
<class 'numpy.ndarray'>
shape (5,)


In [ ]:
# 1D array

arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #1 row and 5 columns


array([[1, 2, 3, 4, 5]])

In [15]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape


(1, 5)

In [ ]:
## 2D array

arr2=np.array([[1,2,3,4,5], [2,3,4,5,6]])
print("array", arr2)
print("shape", arr2.shape)


array [[1 2 3 4 5]
 [2 3 4 5 6]]
shape (2, 5)


In [21]:
n=np.arange(0,10,2)
n.reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4)) # 3 rows and 4 columns


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
## attributes of numpy array

arr = np.array([[1,2,3],[4,5,6]])

print("array\n",arr)
print("shape", arr.shape)
print("number of dimensions", arr.ndim)
print("size (number of elements)",arr.size)
print("data type", arr.dtype) #int64 (may vary based on the system)
print("item size (bytes per element)", arr.itemsize) # 8 bytes for int



array
 [[1 2 3]
 [4 5 6]]
shape (2, 3)
number of dimensions 2
size (number of elements) 6
data type int64
item size (bytes per element) 8


In [ ]:
## numpy vectorized operations

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])


##element wise addition

arr3 = arr1 + arr2 
print("addition", arr3)

## element wise substraction

print("substraction", arr2-arr1)

## element wise multiplication
print("multiplication", arr1*arr2)

## element wise division
print("division", arr1 / arr2)


## return type is also array


addition [11 22 33 44 55]
substraction [ 9 18 27 36 45]
multiplication [ 10  40  90 160 250]
division [0.1 0.1 0.1 0.1 0.1]


In [13]:
## Universal Function
## those function that are apply through all the element of an array

arr = np.array([2,4,6,8,10])

## sqaure 

print("square", np.sqrt(arr))

## exponential

print("exponential", np.exp(arr))

## Sine

print("Sine", np.sin(arr))

## natural log

print("natural log", np.log(arr))

square [1.41421356 2.         2.44948974 2.82842712 3.16227766]
exponential [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Sine [ 0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111]
natural log [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]


In [4]:
## Array Slicing and Indexing 

arr = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])
print("Array \n", arr)

## 2D array




Array 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# now, i want to fetch 1 from this array
## always remember indexing

print(arr[0][0])

print(arr[0:2,2:])

print(arr[1:,1:3])

1
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [10]:
# now i want to get 7,8,11,12

arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
# Modify the array elements 

arr[0][0] = 100

print("modified", arr)

modified [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [35]:
arr[1:] = 100

print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [12]:
## Statistical concepts - Normalization
## to have a mean of 0 and standard deviation of 1

#(normalization is nothing but converting your data in such a way that your mean is 0 and standard deviation is 1)

data = np.array([1,2,3,4,5])

# calculation the mean and stardard deviation
mean = np.mean(data)
print("mean", mean)

stand_dev = np.std(data)
print("standard_deviation", stand_dev)


## normalize the data
normalized_data = (data - mean) / stand_dev
print("Normalized data", normalized_data)


mean 3.0
standard_deviation 1.4142135623730951
Normalized data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [43]:
print("Mean", np.mean(data))
print("Median", np.median(data))
print("Standard Deviation", np.std(data))
print("Variance", np.var(data))

Mean 3.0
Median 3.0
Standard Deviation 1.4142135623730951
Variance 2.0


In [16]:
## Logical operation

data = np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

# data[(data>=6) | (data<=9)]

array([5, 6, 7, 8])